export const food = {
  Полуфабрикаты: [
    {
      title: "Сырники с клубникой",
      category: "Полуфабрикаты",
      subcategory: "Сырники",
      weight: "200 г",
      count: 4,
      price: 229,
      id: 3453467,
    },
    {
      title: "Блинчики с черникой",
      category: "Полуфабрикаты",
      subcategory: "Блины",
      weight: "200 г",
      count: 4,
      price: 229,
      id: 2435679,
    },
    {
      title: "Блинчики с икрой",
      category: "Полуфабрикаты",
      subcategory: "Блины",
      weight: "200 г",
      count: 4,
      price: 229,
      id: 56898,
    },
    {
      title: "2342",
      category: "Полуфабрикаты",
      subcategory: "Блины",
      weight: "200 г",
      count: 4,
      price: 229,
      id: 24356,
    },
    {
      title: "645643",
      category: "Полуфабрикаты",
      subcategory: "Блины",
      weight: "200 г",
      count: 4,
      price: 229,
      id: 634722,
    },
    {
      title: "645643",
      category: "Полуфабрикаты",
      subcategory: "Блины",
      weight: "200 г",
      count: 4,
      price: 229,
      id: 4567457,
    },
  ],
  Роллы: [
    {
      title: "Салат с роллами фирменный (с тунцом и овощами)",
      category: "Роллы",
      subcategory: "Тунец",
      weight: "200 г",
      price: 339,
      id: 564210,
    },
  ],
  Сеты: [
    {
      title: "Сет Для своих",
      category: "Сеты",
      weight: "1390 г",
      count: 41,
      price: 1999,
      id: 921456,
    },
  ],
  Горячее: [
    {
      title: "Бефстроганов запечённый с моцареллой",
      category: "Горячее",
      subcategory: "Мясо",
      weight: "400 г",
      price: 549,
      id: 234696,
    },
  ],
  //"Бизнес-ланчи",
  Салаты: [
    {
      title: "Салат Прованский с курицей-гриль",
      category: "Салаты",
      subcategory: "Хит продаж",
      weight: "300 г",
      price: 389,
      id: 2345456,
    },
  ],
  Супы: [
    {
      title: "Настоящая мясная солянка",
      category: "Супы",
      subcategory: "Классические",
      weight: "300/40 г",
      price: 289,
      id: 83680,
    },
  ],
  Пицца: [
    {
      title: "Пицца с окороком и рукколой",
      category: "Пицца",
      subcategory: "Мясо",
      weight: "600 г",
      price: 559,
      id: 76572,
    },
  ],
  Закуски: [
    {
      title: "Ассорти брускетт с лососем и ростбифом",
      category: "Закуски",
      subcategory: "Холодные",
      weight: "200 г",
      price: 449,
      id: 5345893,
    },
  ],
  Veg: [
    {
      title: "Борщ ВЕГ",
      category: "Veg",
      subcategory: "Супы",
      weight: "300/80/40 г",
      price: 209,
      id: 13245796,
    },
  ],
  Десерты: [
    {
      title: "Пирожное 3 бельгийских шоколада",
      category: "Десерты",
      weight: "120 г",
      price: 289,
      id: 4235678,
    },
  ],
  Хлеб: [
    {
      title: "Тёплые булочки с чесночным маслом 2 шт.",
      category: "Хлеб",
      weight: "100/40 г",
      price: 79,
      id: 423456,
    },
  ],
  Напитки: [
    {
      title: "Морс клюквенный",
      category: "Напитки",
      subcategory: "Морс",
      weight: "500мл",
      price: 179,
      id: 111467,
    },
  ],
  "Детское меню": [
    {
      title: "Овощное лукошко с маслом",
      category: "Детское меню",
      subcategory: "Салаты",
      weight: "200 г",
      price: 149,
      id: 456800,
    },
  ],
  "Банкетное меню": [
    {
      title: "Рулетики овощные",
      category: "Банкетное меню",
      subcategory: "Закуски",
      weight: "750 г",
      price: 1099,
      id: 64567,
    },
  ],
  Соусы: [
    {
      title: "Сырный соус",
      category: "Соусы",
      weight: "40 г",
      price: 69,
      id: 978972,
    },
  ],
};
